### ISSUE TITLE
Adapt plugin prefix to the general prefix style of knockturnmc

### ISSUE THREAD

**Issue by lynxplay** [KnockturnMC/Rest#1]
As of right now, the rest prefix looks like this: ![grafik](https://user-images.githubusercontent.com/32834385/80974435-02c8cb00-8e21-11ea-99e8-ce5e805f53b6.png).
As this project is hosted in the [knockturnmc group](https://github.com/KnockturnMC), it should follow the servers normal prefix style of `[PluginName]`. 
Examples are: ![grafik](https://user-images.githubusercontent.com/32834385/80974545-29870180-8e21-11ea-8575-3731151154fd.png) ![grafik](https://user-images.githubusercontent.com/32834385/80974618-402d5880-8e21-11ea-90ec-19e7961dd6f7.png)

**Comment by danichef** [comment]
Prefix has been changed in commit: 385c8b59aa27f9eaec96ed4f71c762d950e3b142
